services:
  db:
    image: postgres:latest
    container_name: postgres-learning
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "3432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin-learning
    image: dpage/pgadmin4
    ports:
      - "6080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminlocalhost@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local